name: Workflow

on:
  push:
    branches:
      - pipeline

jobs:
  SAST:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # O la versión que estés utilizando

      - name: Set environment
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Validate if the project exists in SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -u $SONAR_TOKEN: \
            -X GET \
            "https://sonarcloud.io/api/projects/search?projects=DevSecOp-tarea-final_${REPO_NAME}&organization=devsecop-tarea-final")
          if [ "$response" -ne 200 ]; then
            echo "El proyecto no existe"
            create_response=$(curl -s -o /dev/null -w "%{http_code}" -u $SONAR_TOKEN: \
              -X POST \
              "https://sonarcloud.io/api/projects/create" \
              -d "name=$REPO_NAME" \
              -d "project=$REPO_NAME" \
              -d "organization=devsecop-tarea-final" \
              -d "visibility=public")
            if [ "$create_response" -eq 200 ]; then
              echo "Proyecto creado"
            else
              echo "Error creando el proyecto"
            fi
            curl -s -o /dev/null -w "%{http_code}" -u $SONAR_TOKEN: \
              -X POST \
              "https://sonarcloud.io/api/project_branches/rename" \
              -d "name=${BRANCH_NAME}" \
              -d "project=$REPO_NAME"
          else
            echo "Proyecto ya existe"
          fi

      - name: Install sonar-scanner
        run: npm install sonar-scanner --save-dev
      
      - name: Set up sonar-project.properties
        run: |
          echo "sonar.projectKey=DevSecOp-tarea-final_${{ github.event.repository.name }}" > sonar-project.properties
          echo "sonar.organization=devsecop-tarea-final" >> sonar-project.properties
          echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
          echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-project.properties
          echo "sonar.sources=./" >> sonar-project.properties
          echo "sonar.language=js" >> sonar-project.properties
          echo "sonar.tests=./tests" >> sonar-project.properties
          echo "sonar.javascript.lcov.reportPaths=coverage/lcov-report/index.html" >> sonar-project.properties
      
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: ./node_modules/.bin/sonar-scanner -X