name: Workflow

on:
  push:
    branches:
      - pipeline

jobs:
  SAST:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # O la versión que estés utilizando

      - name: Set environment
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Validate if the project exists in SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -u $SONAR_TOKEN: \
            -X GET \
            "https://sonarcloud.io/api/projects/search?projects=DevSecOp-tarea-final_${REPO_NAME}&organization=devsecop-tarea-final")
          if [ "$response" -ne 200 ]; then
            echo "El proyecto no existe"
            create_response=$(curl -s -o /dev/null -w "%{http_code}" -u $SONAR_TOKEN: \
              -X POST \
              "https://sonarcloud.io/api/projects/create" \
              -d "name=$REPO_NAME" \
              -d "project=DevSecOp-tarea-final_${REPO_NAME}" \
              -d "organization=devsecop-tarea-final" \
              -d "visibility=public")
            if [ "$create_response" -eq 200 ]; then
              echo "Proyecto creado"
            else
              echo "Error creando el proyecto"
            fi
            curl -s -o /dev/null -w "%{http_code}" -u $SONAR_TOKEN: \
              -X POST \
              "https://sonarcloud.io/api/project_branches/rename" \
              -d "name=${BRANCH_NAME}" \
              -d "project=$REPO_NAME"
          else
            echo "Proyecto ya existe"
          fi

      - name: Install sonar-scanner
        run: npm install sonar-scanner --save-dev
      
      - name: Set up sonar-project.properties
        run: |
          echo "sonar.projectKey=DevSecOp-tarea-final_${{ github.event.repository.name }}" > sonar-project.properties
          echo "sonar.organization=devsecop-tarea-final" >> sonar-project.properties
          echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
          echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-project.properties
          echo "sonar.sources=./" >> sonar-project.properties
          echo "sonar.language=js" >> sonar-project.properties
          echo "sonar.javascript.lcov.reportPaths=coverage/lcov-report/index.html" >> sonar-project.properties
      
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: ./node_modules/.bin/sonar-scanner

      - name: Quality Gate Status
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=DevSecOp-tarea-final_${REPO_NAME}" | jq -r '.projectStatus.status')
          echo "Quality Gate status: $status"
          
          if [ "$status" != "OK" ]; then
            echo "Quality Gate failed."
            #exit 1
          fi

  SCA:
    needs: SAST
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Mkdir reports
        run: mkdir reports

      - name: npm install
        run: npm install

      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env: 
          JAVA_HOME: /opt/jdk
        id: depcheck
        with:
          project: ${{ github.event.repository.name }}
          path: '.'
          format: 'HTML'
          args: >
            --out ./reports 
            --failOnCVSS 20

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./reports
          
  imagen:
    needs: SCA
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: pimpo7
            password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Build Docker image
        run: |
            docker build -t laboratorio-final:latest .
            
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: laboratorio-final:latest
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt
